catalog_path: {{ CATALOG }}
mapper_config:
  function: open_zarr
  kwargs:
    data_path: {{ RADIATIVE_FLUX_DATASET }}
res: c384
shuffle_samples: false
shuffle_timesteps: false
timesteps:
# - '20200204.013000'
- '20200207.193000'
- '20200211.073000'
- '20200211.103000'
- '20200212.193000'
- '20200216.103000'
- '20200218.103000'
- '20200219.163000'
- '20200222.103000'
- '20200223.223000'
timesteps_per_batch: 10
unstacked_dims:
- z
# subsample_ratio: 0.015625
variable_names:
- cos_zenith_angle
- surface_geopotential
- air_temperature
- specific_humidity
- latitude
- shortwave_transmissivity_of_atmospheric_column
- override_for_time_adjusted_total_sky_downward_longwave_flux_at_surface
