catalog_path: {{ CATALOG }}
mapper_config:
  function: open_nudge_to_fine
  kwargs:
    cache_size_mb: 4000
    data_path: {{ SIMULATION_ROOT }}/nudged
    nudging_variables:
    - air_temperature
    - specific_humidity
    - eastward_wind
    - northward_wind
    datasets:
    - nudging_tendencies.zarr
    - state_after_timestep.zarr
    physics_timestep_seconds: 450.0
res: c384
shuffle_samples: false
shuffle_timesteps: false
timesteps:
# - '20200204.013000'
- '20200207.193000'
- '20200211.073000'
- '20200211.103000'
- '20200212.193000'
- '20200216.103000'
- '20200218.103000'
- '20200219.163000'
- '20200222.103000'
- '20200223.223000'
timesteps_per_batch: 10
unstacked_dims:
- z
# subsample_ratio: 0.015625
variable_names:
- cos_zenith_angle
- surface_geopotential
- air_temperature
- specific_humidity
- eastward_wind
- northward_wind
- latitude
- dQ1
- dQ2
- dQu
- dQv
