cache:
  in_memory: false
derived_output_variables: []
model_type: dense
output_transforms: []
random_seed: 3
sample_dim_name: sample
hyperparameters:
  callbacks:
  - kwargs:
      monitor: val_loss
      patience: 25
    name: EarlyStopping
  clip_config:
    clip:
      air_temperature:
        start: 25
        step: null
        stop: null
      dQ1:
        start: 3
        step: null
        stop: null
      dQ2:
        start: 3
        step: null
        stop: null
      specific_humidity:
        start: 25
        step: null
        stop: null
  dense_network:
    depth: 3
    gaussian_noise: 0
    kernel_regularizer:
      kwargs:
        l: 0.0001
      name: l2
    spectral_normalization: false
    width: 419
  input_variables:
  - cos_zenith_angle
  - surface_geopotential
  - air_temperature
  - specific_humidity
  - latitude
  loss:
    loss_type: mae
    scaling: standard
    weight: 1
  normalization_fit_samples: 8000
  optimizer_config:
    kwargs:
      learning_rate: 0.00014
    learning_rate_schedule: null
    name: Adam
  output_limit_config:
    limits:
      dQ1:
        max: 0.002
        min: -0.002
      dQ2:
        max: 1.5e-06
        min: -1.5e-06
  output_variables:
  - dQ1
  - dQ2
  training_loop:
    batch_size: 512
    epochs: 500
    in_memory: true
    shuffle_buffer_size: 50000
  weights: null
