cache:
  in_memory: false
derived_output_variables: []
hyperparameters:
  callbacks:
  - kwargs:
      monitor: val_loss
      patience: 25
    name: EarlyStopping
  clip_config:
    clip:
      air_temperature:
        start: 25
        step: null
        stop: null
      dQu:
        start: 3
        step: null
        stop: null
      dQv:
        start: 3
        step: null
        stop: null
      specific_humidity:
        start: 25
        step: null
        stop: null
  dense_network:
    depth: 3
    gaussian_noise: 0.0
    kernel_regularizer:
      kwargs:
        l: 0.0001
      name: l2
    spectral_normalization: false
    width: 419
  input_variables:
  - cos_zenith_angle
  - surface_geopotential
  - air_temperature
  - specific_humidity
  - latitude
  - northward_wind
  - eastward_wind
  loss:
    loss_type: mae
    scaling: standard
    weight: 1.0
  normalization_fit_samples: 8000
  optimizer_config:
    kwargs:
      learning_rate: 0.00014
    learning_rate_schedule: null
    name: Adam
  output_limit_config:
    limits:
      dQu:
        max: 0.016
        min: -0.016
      dQv:
        max: 0.016
        min: -0.016
  output_variables:
  - dQu
  - dQv
  training_loop:
    batch_size: 512
    epochs: 500
    in_memory: true
    shuffle_buffer_size: 50000
  weights: null
model_type: dense
output_transforms: []
random_seed: 2
